### ISSUE TITLE
Network permission missing?

### ISSUE THREAD

**Issue by mttkay** [flathub/org.twinery.Twine#1]
I am not familiar with flatpak internals, but I noticed that I cannot import new formats from a remote destination in the flatpak version of Twine; it fails with the following error:

![twine_net_error](https://user-images.githubusercontent.com/102802/151655240-1f58935e-5b1d-479d-abd7-94e10bf30381.png)

The URL is taken from https://github.com/lazerwalker/twison, and I can curl it from my host machine successfully:

```
https://lazerwalker.com/twison/format.js
```

So I wondered whether this could be a permission error due to flatpaks running in containers (IIUC). I checked the app permissions:

```
[9:59:37] ~ flatpak info --show-permissions org.twinery.Twine      
[Context]
shared=ipc;
sockets=x11;
devices=dri;
filesystems=xdg-download;xdg-documents/Twine:create;
```

According to https://docs.flatpak.org/en/latest/sandbox-permissions-reference.html, this is missing the `network` permission:

```
--share=network | Access the network [2]
```

I tried to experiment with this by doing 

```
[9:57:02] ~ sudo flatpak override com.twinery.Twine --share=network
```

but this seems to have no effect.

Any ideas what's going on here?

**Comment by mttkay** [comment]
Yeah pretty sure that's the problem; looking at permissions for Slack, for instance:

```
[Context]
shared=network;ipc;
...
```

same for Dropbox and other networked apps.

**Comment by mttkay** [comment]
A workaround is to first download the remote format to a local file on your host machine, then use a `file://` URL in the import dialog.

But I would still consider this a bug, since it breaks existing functionality.

**Comment by hfiguiere** [comment]
You can use Flatseal to enable it in the mean time.

https://flathub.org/apps/details/com.github.tchx84.Flatseal

**Comment by mttkay** [comment]
Thanks for pointing this out, I was not aware of it; this looks really useful :+1:

**Comment by SISheogorath** [comment]
Sorry for being late to the party, I didn't watch the repository 🤦🏻 

Anyway, it was an intentional decision to no provide network access, but I can see why it's useful. Therefore let's go with it, people can restrict network access down the line.
