### ISSUE TITLE
Update to 2.7.1

### ISSUE THREAD

**Issue by lucyferu** [flathub/org.twinery.Twine#19]
hello!

mostly wondering if and/or when the flatpak app will be updated to the latest version of Twine?

**Comment by SISheogorath** [comment]
Actually it's already released, just the metadata is wrong. I'm fixing the metadata.

**Comment by lucyferu** [comment]
oh, thank you, sorry about that.

**Comment by SISheogorath** [comment]
No need to be sorry, it was completely right to point out the wrong version :) It just had different reason than you expected ^^
